### ISSUE TITLE
Functon normalize_whitespace being applied regardless of conditions

### ISSUE THREAD

**Issue by ogabrielluiz** [jfilter/clean-text#13]
Hi! Your project is very useful!
 
https://github.com/jfilter/clean-text/blob/d32aa94ad20226aa3626aa000fb9454ec16c96ab/cleantext/clean.py#L86

I was wondering why this function is applied like this instead of having a condition for it to be applied.

Is fixing whitespaces absolutely required?

Thanks!

**Comment by jfilter** [comment]
Yes, good idea. ;)
