### ISSUE TITLE
clean function error

### ISSUE THREAD

**Issue by sasi2400** [jfilter/clean-text#16]
I just followed the example in the readme and got this issue
```
>>> clean("he;;p", fix_unicode=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: clean() got an unexpected keyword argument 'fix_unicode'
```

**Comment by jfilter** [comment]
What package (exact name) did you install?

**Comment by sasi2400** [comment]
pip install clean-text
and also pip install cleantext

**Comment by sasi2400** [comment]
I got it. The mistake was that I first installed the cleantext.
I needed to uninstall both and reinstall the clean-text 
All good now!
