### ISSUE TITLE
Add Scikit-learn compatible api for function clean

### ISSUE THREAD

**Issue by sadra-barikbin** [jfilter/clean-text#21]
Hi there!

I propose to add the Scikit-learn compatible api for the funcion `clean`. It's as easy as making a class subclassing scikit-learn `TransformerMixin`  and implementing the `fit` and `transform` methods.

This api has the advantage that enables the user to integrate the `clean` function into the preprocessing pipeline and examine effects of various options that `clean` provides, in the downstream task.

**Comment by jfilter** [comment]
Hey @sadra-barikbin, thanks for the suggestion and the PR. I will take a look at it when I have some more time.
