### ISSUE TITLE
Issue with 'fix_unicode' (unexpected keyword argument)

### ISSUE THREAD

**Issue by jcontd** [jfilter/clean-text#35]
I'm encountering the following error any time I try to run `clean`:

`clean() got an unexpected keyword argument 'fix_unicode'`

When I try to remove the 'fix_unicode' step and just go on to the next one, the same error occurs each time. I was able to use this successfully as recently as a few months ago, but now I'm no longer able to. The only difference I can think of in usage is that I'm now working on an M2 Mac (which has created issues in other cases, packages, etc., as many have pointed out), but I'm unsure whether this would have an impact here.

Has anyone else encountered this or have a sense of how to address it?

<img width="916" alt="1" src="https://user-images.githubusercontent.com/84885793/224563945-e1cba174-625d-450e-a586-6b4221688342.png">

**Comment by sixf0ur** [comment]
Make sure you don't have another function defined as "clean".

**Comment by jcontd** [comment]
Alas, it's the only one defined as "clean" here.

Really appreciate the help, though — thank you! Any other ideas what the problem could be?

**Comment by sixf0ur** [comment]
Try to uninstall the package and reinstall it with  unidecode
```
pip uninstall clean-text
```
```
pip install clean-text[gpl]
```

**Comment by jcontd** [comment]
That worked!! Thank you so much! 🎉
