### ISSUE TITLE
TypeError: clean() got an unexpected keyword argument 'no_urls'

### ISSUE THREAD

**Issue by ArjunSarihyan** [jfilter/clean-text#6]
processed_cmts = []
for cmt in df_user_max['comment_body']:
    
    processed_text = clean(cmt,
                           no_urls=True, no_emails=True, no_numbers=True, no_digits=True, 
                           no_currency_symbols=True, no_punct=True, 
                           replace_with_url="<URL>", 
                           replace_with_email="<EMAIL>",
                           replace_with_phone_number="<PHONE>",
                           replace_with_number="<NUMBER>",
                           replace_with_digit="0",
                           replace_with_currency_symbol="<CUR>",
                           lang="en")
    processed_cmts.append(processed_text)
print(len(processed_cmts))

Error---------->

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-67-aeb8a53467e8> in <module>
     12                            replace_with_digit="0",
     13                            replace_with_currency_symbol="<CUR>",
---> 14                            lang="en")
     15     processed_cmts.append(processed_text)
     16 print(len(processed_cmts))

TypeError: clean() got an unexpected keyword argument 'no_urls'

**Comment by jfilter** [comment]
Are you sure the function `clean` is from `clean-text`?

**Comment by mbednarski** [comment]
@ArjunSarihyan 

You probably installed `cleantext` instead of `clean-text`.
