### ISSUE TITLE
doesn't work with dataframe (csv file)

### ISSUE THREAD

**Issue by widedM** [jfilter/clean-text#7]
Hi,
i have a csv file with multiple columns: post_id, post_text
and im trying to clean the post_text which is a dataframe and i read it from a csv file. The problem that the clean method doesn't take all the text but it tooks some word from every line of the dataframe ! 
please help.
you can find a txt file (csv are not allowed here) and two screenshots, one is for real data and the other is for the output of clean()

![clean](https://user-images.githubusercontent.com/51926770/80798217-27fcd580-8ba4-11ea-9a41-c64c06134495.PNG)
![data](https://user-images.githubusercontent.com/51926770/80798219-29c69900-8ba4-11ea-8e36-acf70f73a56e.PNG)

[posts.txt](https://github.com/jfilter/clean-text/files/4563379/posts.txt)

**Comment by jfilter** [comment]
Change the first line to:
`d=data['Post Message'].tolist()`

This is not a problem of this library but a 'feature' of pandas. I personally also find it unintuitive.
