### ISSUE TITLE
whitespace between emojis

### ISSUE THREAD

**Issue by cod3licious** [jfilter/clean-text#9]
Thanks for this great library! :)

To facilitate tokenisation it would be great if additional whitespace could be added before and after each emoji.

**Comment by jfilter** [comment]
I'm not sure if this can be easily done. There are emojis that [consist of several sub-emojis](https://stackoverflow.com/a/49242754/4028896_/). And I don't want to go into the direction of writing an emoji tokenizer just to add whitespace.

If people need some very special emoji handling, this other package may help: https://github.com/carpedm20/emoji

(If somebody comes up with an easy way to accomplish: I'm open to pull requests.)
